language: python
python:
  # - "2.7", problem with travis testing environment; see #1
  - "3.6"
install: "pip install -e .[test]"
script: "py.test -v --cov hypothesis_geojson --cov-report term-missing"
